/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calculator_1(char *host)
{
	CLIENT *clnt;
	double  *result_1;
	my_numbers  addition_1_arg;
	double  *result_2;
	my_numbers  subtraction_1_arg;
	double  *result_3;
	my_numbers  multiplication_1_arg;
	double  *result_4;
	my_numbers  division_1_arg;
	
	double val1,val2,val3, val4 ;
	double val5,val6,val7, val8 ;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULATOR, CALC, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
        char choice;

    printf("Please select a choice for the operation you want.\n");
    printf("A: Addition\n");
    printf("B: Subtraction\n");
    printf("C: Multiplication\n");
    printf("D: Division\n");
    scanf("%c", &choice);
    
    switch(choice) {
        case 'A':
            printf("Enter 2 digits to add\n");
            printf("Value 1: ");
            scanf("%lf", &val1);
            
            printf("Value 2: ");
            scanf("%lf", &val2);
            
            addition_1_arg.a = val1;
            addition_1_arg.b = val2;
            
            result_1 = addition_1(&addition_1_arg, clnt);
	        if (result_1 == (double *) NULL) {
			   clnt_perror (clnt, "call failed");
	        }
	        printf("Result of addition is %lf:", *result_1);
            break;
        case 'B':
            printf("Enter 2 digits to subtract\n");
            printf("Value 1: ");
            scanf("%lf", &val3);
            printf("Value 2: ");
            scanf("%lf", &val4);
            
            subtraction_1_arg.a = val3;
            subtraction_1_arg.b = val4;
            
           result_2 = subtraction_1(&subtraction_1_arg, clnt);
	       if (result_2 == (double *) NULL) {
			  clnt_perror (clnt, "call failed\n");
			  }
		    printf("Result of subtraction is %lf:\n", *result_2);
            break;
        case 'C':
            printf("Enter 2 digits to multiply\n");
            printf("Value 1: ");
            scanf("%lf", &val5);
            printf("Value 2: ");
            scanf("%lf", &val6);
            
            multiplication_1_arg.a = val5;
            multiplication_1_arg.b = val6;
            
            result_3 = multiplication_1(&multiplication_1_arg, clnt);
	        if (result_3 == (double *) NULL) {
			   clnt_perror (clnt, "call failed\n");
			   }
		    printf("Result of multiplication is %lf:\n", *result_3);
            break;
        case 'D':
            printf("Enter 2 digits to multiply\n");
            printf("Value 1: ");
            scanf("%lf", &val7);
            printf("Value 2: ");
            scanf("%lf", &val8);
            
            division_1_arg.a = val7;
            division_1_arg.b = val8;
            
            result_4 = division_1(&division_1_arg, clnt);
            if (result_4 == (double *) NULL) {
				clnt_perror (clnt, "call failed");
				}
			printf("Result of division is %lf:\n", *result_4);
            break;
        default:
            printf("Please select a valid choice.\n");
    }
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}  
	  host = argv[1];
	  calculator_1 (host);
exit (0);
}
