/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct my_numbers {
	double a;
	double b;
	double c;
};
typedef struct my_numbers my_numbers;

#define CALCULATOR 0x23453333
#define CALC 1

#if defined(__STDC__) || defined(__cplusplus)
#define addition 1
extern  double * addition_1(my_numbers *, CLIENT *);
extern  double * addition_1_svc(my_numbers *, struct svc_req *);
#define subtraction 2
extern  double * subtraction_1(my_numbers *, CLIENT *);
extern  double * subtraction_1_svc(my_numbers *, struct svc_req *);
#define multiplication 3
extern  double * multiplication_1(my_numbers *, CLIENT *);
extern  double * multiplication_1_svc(my_numbers *, struct svc_req *);
#define division 4
extern  double * division_1(my_numbers *, CLIENT *);
extern  double * division_1_svc(my_numbers *, struct svc_req *);
extern int calculator_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define addition 1
extern  double * addition_1();
extern  double * addition_1_svc();
#define subtraction 2
extern  double * subtraction_1();
extern  double * subtraction_1_svc();
#define multiplication 3
extern  double * multiplication_1();
extern  double * multiplication_1_svc();
#define division 4
extern  double * division_1();
extern  double * division_1_svc();
extern int calculator_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_my_numbers (XDR *, my_numbers*);

#else /* K&R C */
extern bool_t xdr_my_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
