/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

double *
addition_1_svc(my_numbers *argp, struct svc_req *rqstp)
{
	static double  result;
	
	result = argp->a + argp->b;
	
	return &result;
}

double *
subtraction_1_svc(my_numbers *argp, struct svc_req *rqstp)
{
	static double  result;
	
	result = argp->a - argp->b;

	return &result;
}

double *
multiplication_1_svc(my_numbers *argp, struct svc_req *rqstp)
{
	static double  result;

	result = argp->a * argp->b;
	
	return &result;
}

double *
division_1_svc(my_numbers *argp, struct svc_req *rqstp)
{
	static double  result;

	result = argp->a / argp->b;

	return &result;
}
